import Head from "next/head";
// import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>info - wiktrek.xyz</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <a></a>
      </main>
    </>
  );
}
