import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>info - wiktrek.xyz</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Link href="/afirmation">Afirmation</Link>
          <Link href="/fjk"></Link>
        </div>
      </main>
    </>
  );
}
