import Head from "next/head";
import Link from "next/link";

export default function Page() {
  return (
    <>
      <Head>
        <title>info - wiktrek.xyz</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" h-screen items-center justify-center text-center text-5xl  no-underline">
        <div>
          <Link href="/afirmation" className="">
            Afirmation
          </Link>
          <Link href="/"></Link>
        </div>
      </main>
    </>
  );
}
