import { type NextPage } from "next";
import Head from "next/head";
// import Link from "next/link";
import * as THREE from "three";
const Home: NextPage = () => {
  const scene = new THREE.Scene();

  // Option 2: Import just the parts you need.
  import { Scene } from "three";

  const scene = new Scene();
  return (
    <>
      <Head>
        <title>info - wiktrek.xyz</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div></div>
      </main>
    </>
  );
};

export default Home;
