import Head from "next/head";
// import Link from "next/link";
import * as THREE from "three";
const BackGround = () => {
  const { Scene } = THREE;
  const scene = new Scene();
  const text = new THREE.TextGeometry("Hello three.js!", {
    font: "",
    size: 80,
    height: 5,
    curveSegments: 12,
    bevelEnabled: true,
    bevelThickness: 10,
    bevelSize: 8,
    bevelOffset: 0,
    bevelSegments: 5,
  });
  scene.add(text);
  return (
    <>
      <Head>
        <title>info - wiktrek.xyz</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div></div>
      </main>
    </>
  );
};

export default BackGround;
