import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>info - wiktrek.xyz</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <ul>
          <li>
            <Link href="/designs/one">one</Link>
          </li>
          <li>
            <Link href="/designs/two">two</Link>
          </li>
        </ul>
      </main>
    </>
  );
};

export default Home;
