import { type NextPage } from "next";
import Head from "next/head";
// import Link from "next/link";
import BackGround from "./components/bg";
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>info - wiktrek.xyz</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <BackGround />
      </main>
    </>
  );
};

export default Home;
