import { type NextPage } from "next";
import Head from "next/head";
// import Image from "next/image";
import BackGround from "../components/bg";
import Person from "../components/person";
const Design: NextPage = () => {
  return (
    <>
      <Head>
        <title>info - wiktrek.xyz</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className=" absolute mx-auto text-center">
          <div className="mx-auto flex h-screen w-screen items-center justify-center text-center">
            <div className="grid grid-cols-4 gap-4">
              <Person />
              <Person />
              <Person />
              <Person />
              <Person />
              <Person />
              <Person />
              <Person />
            </div>
          </div>
        </div>

        <BackGround />
      </main>
    </>
  );
};
export default Design;
