import { type NextPage } from "next";
import Head from "next/head";
import BackGround from "../components/bg";
const Design: NextPage = () => {
  return (
    <>
      <Head>
        <title>info - wiktrek.xyz</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <BackGround />
        <div className="absolute right-0 bottom-1 z-50 text-4xl text-white">
          <a>Wiktrek</a>
        </div>
      </main>
    </>
  );
};
export default Design;
