import { type NextPage } from "next";
import Head from "next/head";
// import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>first design - info</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div>
          <a>...</a>
        </div>
      </main>
    </>
  );
};

export default Home;
