import { type NextPage } from "next";
import Head from "next/head";
import Tool from "../components/tool";
import BackGround from "../components/bg";
const Design: NextPage = () => {
  return (
    <>
      <Head>
        <title>Wiktrek portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className=" absolute flex h-screen w-screen items-center justify-center">
          <div className="grid grid-cols-4 items-center gap-16 object-center">
            <Tool
              name={"wiktrek.xyz"}
              description={"my website"}
              url={"https://wiktrek.xyz"}
              img={"/next.png"}
            />
            <Tool
              name={"poll app"}
              description={"polls"}
              url={"https://wiktrek.xyz/projects/poll"}
              img={"/next.png"}
            />
            <Tool
              name={"link shortener"}
              description={"link shortener"}
              url={"https://wiktrek.xyz/projects/url"}
              img={"/next.png"}
            />
            <Tool
              name={"rust"}
              description={"my rust repository"}
              url={"https://github.com/wiktrek/rust"}
              img={"/rust.png"}
            />
            <Tool
              name={"wiktrekbot"}
              description={"Discord bot"}
              url={"https://github.com/wiktrek/wiktrekbot"}
              img={"/discord.png"}
            />
            <Tool
              name={"info.wiktrek.xyz"}
              description={"another website"}
              url={"https://info.wiktrek.xyz"}
              img={"/next.png"}
            />
            <Tool
              name={"svelte.wiktrek.xyz"}
              description={"antoher website but made using svelte"}
              url={"https://svelte.wiktrek.xyz"}
              img={"/svelte.png"}
            />
          </div>
        </div>
        <BackGround />
      </main>
    </>
  );
};
export default Design;
