import { type NextPage } from "next";
import Head from "next/head";
import BackGround from "../components/bg";
const Design: NextPage = () => {
  return (
    <>
      <Head>
        <title>Wiktrek portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className=" absolute flex h-screen w-screen items-center justify-center">
          <div className="h-64 w-72  rounded-2xl bg-slate-50 text-center ">
            <a>Some text about me</a>
          </div>
          <div className="h-64 w-72  rounded-2xl bg-slate-50 text-center ">
            <a>Some text about me</a>
          </div>
          <div className="h-64 w-72  rounded-2xl bg-slate-50 text-center ">
            <a>Some text about me</a>
          </div>
          <div className="h-64 w-72  rounded-2xl bg-slate-50 text-center ">
            <a>Some text about me</a>
          </div>
        </div>
        <BackGround />
      </main>
    </>
  );
};
export default Design;
