import { type NextPage } from "next";
import Head from "next/head";
import Tool from "../components/tool";
import BackGround from "../components/bg";
const Design: NextPage = () => {
  return (
    <>
      <Head>
        <title>Wiktrek portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className=" absolute flex h-screen w-screen items-center justify-center">
          <div className="grid grid-cols-4 items-center gap-16 object-center">
            <Tool
              name={"next.js "}
              description={"next.js"}
              url={"https://nextjs.org/"}
              img={"/next.png"}
            />
            <Tool
              name={"rust"}
              description={"rust"}
              url={"https://www.rust-lang.org/"}
              img={"/rust.png"}
            />
            <Tool
              name={"typescript"}
              description={"typescript"}
              url={"https://www.typescriptlang.org/"}
              img={"/typescript.png"}
            />
          </div>
        </div>
        <BackGround />
      </main>
    </>
  );
};
export default Design;
