import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Tweet from "../components/twitter";
const Twitter: NextPage = () => {
  const [input, setInput] = useState("");

  interface User {
    name: string;
    image: string;
  }
  interface Tweet {
    user: User;
    createdAt: string;
    tweet: string;
  }
  const user: User = {
    name: "wiktrek",
    image: "/image.png",
  };
  const tweet: Tweet = {
    user: {
      name: "wiktrek",
      image: "/image.png",
    },
    createdAt: "07.02.2023",
    tweet: "hi",
  };

  return (
    <>
      <Head>
        <title>Twitter - wiktrek.xyz</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg- h-screen w-screen bg-slate-600">
        <div className="flex items-center justify-center">
          <div className="grid grid-cols-1 gap-2">
            <div className="h-48 w-96 rounded border-2 bg-black">
              <Image alt="image" src={user.image} width="40" height="40" />
              <textarea
                className="form-control roundedborder m-0 h-24
                w-full resize-none overflow-hidden border-solid bg-transparent bg-clip-padding px-3 py-1.5 text-base
                text-white  transition ease-in-out focus:bg-transparent focus:text-white focus:outline-none"
                placeholder="What's happening?"
                value={input}
                onChange={(e) => setInput(e.target.value)}
              />
              <button className="bottom-96 h-12 w-12 rounded-xl bg-[#1a8cd8] font-bold text-[#e7f3fb]">
                Tweet
              </button>
            </div>
            <Tweet tweet={tweet} />
            <Tweet tweet={tweet} />
            <Tweet tweet={tweet} />
            <Tweet tweet={tweet} />
          </div>
        </div>
      </main>
    </>
  );
};
export default Twitter;
