import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
const Design: NextPage = () => {
  return (
    <>
      <Head>
        <title>info - wiktrek.xyz</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div>
          <div>
            <Image alt="next" src="/next.png" width="100" height="50" />
            <a>Message</a>
          </div>
        </div>
      </main>
    </>
  );
};
export default Design;
