import { type NextPage } from "next";
import Head from "next/head";
import BackGround from "../components/bg";
import Item from "../components/item";
const Design: NextPage = () => {
  return (
    <>
      <Head>
        <title>info - wiktrek.xyz</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className="absolute mx-auto text-center">
          <div className="flex">
            <div className="grid">
              <Item />
              <Item />
              <Item />
              <Item />
              <Item />
              <Item />
              <Item />
              <Item />
              <Item />
            </div>
          </div>
        </div>
        <BackGround />
      </main>
    </>
  );
};
export default Design;
