import { type NextPage } from "next";
import Head from "next/head";
import BackGround from "../components/bg";
const Design: NextPage = () => {
  return (
    <>
      <Head>
        <title>info - wiktrek.xyz</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className="absolute mx-auto text-center">
          <a>Two</a>
        </div>

        <BackGround />
      </main>
    </>
  );
};
export default Design;
