import Head from "next/head";
import Link from "next/link";
import Navbar from "~/components/navbar";

export default function Page() {
  return (
    <>
      <Head>
        <title>info - wiktrek.xyz</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" h-screen items-center justify-center text-center text-6xl  no-underline">
        <Navbar />
        <div className=" grid grid-cols-1">
          <Link href="/stuff/twitter" className="">
            Twitter
          </Link>
        </div>
      </main>
    </>
  );
}
