import Head from "next/head";
import { TrendingComponent, LeftComponent } from "~/components/Twitter";

export default function Page() {
  return (
    <>
      <Head>
        <title>info - wiktrek.xyz</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" h-screen items-center justify-center  bg-[#14171A] text-center text-2xl text-[#F5F8FA] no-underline">
        <div className="h-32 w-32 rounded bg-[#657786]">
          Trending
          <TrendingComponent text="Poland" tweets={1} />
          <LeftComponent options="home, explore" />
        </div>
      </main>
    </>
  );
}
